### ISSUE TITLE
This does something.

### ISSUE THREAD

**Issue by jimmyadaro** [Aerolab/perfect#1]
I just installed this in my 2011 Macbook Pro and it does _something_. Any idea what can I do to make it do nothing again? 

Thanks in advance.

**Comment by RobertoGonzalez** [comment]
What you’re experiencing might simply be the sheer joy of using a perfect piece of software. This is normal and not a cause of concern. 

However, you might have been the victim of a stray cosmic ray that caused a flipped bit somewhere in your hard drive and therefore altered the program. You should ensure your version of Perfect™ has a SHA256 hash of e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 . 

Interestingly, this exactly matches the hash of /dev/null, which is a highly improbable event.
